"""Constants for POLARIS infrastructure."""

# Network constants
MIN_PORT = 1
MAX_PORT = 65535
DEFAULT_WILDFIRE_PORT = 5000

# HTTP status codes
HTTP_STATUS_MIN_SUCCESS = 200
HTTP_STATUS_MAX_SUCCESS = 300

# Default configuration values
DEFAULT_MAX_STATES_PER_SYSTEM = 5000

# Time constants (in milliseconds/seconds as appropriate)
MILLISECONDS_PER_SECOND = 1000

# String validation
MIN_ID_LENGTH = 1

# Timeout constants (in seconds)
DEFAULT_CONNECTOR_TIMEOUT = 10.0
DEFAULT_SWIM_TIMEOUT = 30.0
DEFAULT_MONITORING_INTERVAL = 30.0
DEFAULT_COOLDOWN_SECONDS = 60

# LLM constants
DEFAULT_MAX_TOKENS = 8192
DEFAULT_MAX_TOKENS_REASONING = 4096
DEFAULT_MAX_TOKENS_DIAGNOSTICIAN = 1024
DEFAULT_MAX_TOKENS_PLANNER = 2048
DEFAULT_JSON_INDENT = 2
DEFAULT_GOOGLE_MODEL = "gemini-3-flash-preview"

# Threshold strategy defaults
DEFAULT_COOLDOWN_SECONDS = 60

# Performance thresholds
DEFAULT_STD_DEVIATION_THRESHOLD = 5.0
DEFAULT_EXECUTION_TIME_NORMALIZATION = 5.0
